name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build the Preprocess image
        run: docker build ./src/preprocess_data --tag ${{ secrets.DOCKERHUB_USERNAME }}/fl_preprocess
      - name: Push the Preprocess image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fl_preprocess
      - name: Build the Train image
        run: docker build ./src/train --tag ${{ secrets.DOCKERHUB_USERNAME }}/fl_train
      - name: Push the Train image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fl_train
      - name: Build the Test image
        run: docker build ./src/test --tag ${{ secrets.DOCKERHUB_USERNAME }}/fl_test
      - name: Push the Test image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fl_test
      - name: Build the Deploy image
        run: docker build ./src/deploy_model --tag ${{ secrets.DOCKERHUB_USERNAME }}/fl_deploy
      - name: Push the Deploy image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fl_deploy